name: ML Model CI

on:
  push:
    paths:
      - 'ml-model/**'
  pull_request:
    paths:
      - 'ml-model/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ml-model

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: |
          export PYTHONPATH=src
          pytest